# Generated by Django 4.2.3 on 2023-07-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isnb',
            new_name='isbn',
        ),
    ]
